// <auto-generated />
using BuildNotifier.Data.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BuildNotifier.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.5");

            modelBuilder.Entity("BuildNotifier.Data.Models.DB.PlanChat", b =>
                {
                    b.Property<string>("PlanName")
                        .HasColumnType("TEXT");

                    b.Property<string>("ChatId")
                        .HasColumnType("TEXT");

                    b.HasKey("PlanName", "ChatId");

                    b.HasIndex("ChatId");

                    b.HasIndex("PlanName");

                    b.ToTable("PlanChats");
                });
#pragma warning restore 612, 618
        }
    }
}
